version: '3.7'

services: 
  db:
    image: postgres:14
    ports:
      - '5432:5432'
    expose: 
      - '5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /var/run/postgresql:/var/run/postgresql
  redis:
    image: redis:6.2.7-alpine
    ports:
      - '6379:6379'
    expose:
     - '6379'
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file:
      - .env.development
    depends_on:
      - db
      - redis
